### ISSUE TITLE
Баг кодировок. Русские надписи некорректно воспринимаются интерфейсом.

### ISSUE THREAD

**Issue by dkondagit** [EduVrn/Challenge#28]
Уже на этапе прихода в контроллер вместо кириллицы кракозябры. Проблема на стороне страницы (с высокой вероятностью).

**Comment by breakbreak15** [comment]
Если судить во этой статье https://habrahabr.ru/post/147843/, то получается, что проблема в том, что-то происходит переход от кодировки UTF-8 к Win-1252.
