### ISSUE TITLE
Настроить публичный сервер

### ISSUE THREAD

**Issue by EduVrn** [EduVrn/Challenge#8]
1. обеспечить доступ к интерфейсу по порту - 80
2. настроить инсталяцию последней сборки по коммиту в мастер ветку гитхаба
3. желательно - описать конфигурацию в вики

**Comment by joinedserg** [comment]
на данном сервере по-умолчанию не запущены все необходимые для continuos integration сервисы, поскольку они в совокупности требуют больше памяти, чем есть на сервере
