### ISSUE TITLE
Редактирование картинок

### ISSUE THREAD

**Issue by EduVrn** [EduVrn/Challenge#9]
1. Интерфейс редактирования картинок (локальное хранилище, URL)
2. Серверные API для загрузки картинок
3. Настройка среды храниения картинок (nginx, jackrabbit,...)

**Comment by joinedserg** [comment]
по разделению помню, но есть вопрос об интерфейсе взаимодействия, а именно как делать запросы:
1. клиент <-> сервер <-> сервис хранения картинок(JackRabbit)
2. клиент<->сервис хранения картинок(JackRabbit) <-> база (за правами доступа)

В первом случае подойдет создание единого интерфейса обращения за данными,
во втором он не нужен(второй вариант мне кажется наиболее предпочтительным)
